---
- hosts: pi
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=yes cache_valid_time=3600

  roles:
    - raspberry-pi

  tasks:
    - name: Upgrade distribution
      import_tasks: tasks/upgrade-system.yml

    - name: Set proper timezone
      import_tasks: tasks/set-timezone.yml

    - name: Disable swap file
      import_tasks: tasks/configure-swap.yml

    - name: Install Docker
      import_tasks: tasks/install-docker.yml

  post_tasks:
    - name: Clean unused dependencies
      ansible.builtin.apt: autoremove=yes

  vars:
    dist_upgrade: true
    eeprom_update: true

    timezone: America/New_York

    swap_enabled: false
    bt_enabled: false
    wifi_enabled: false

    cpu_overclock: true

    docker_install: true
