---
- hosts: pi
  become: yes

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt: update_cache=yes upgrade=safe

  tasks:
    - name: Set proper timezone
      import_tasks: tasks/set-timezone.yml

    - name: Disable swap file
      import_tasks: tasks/configure-swap.yml

    - name: Configure Bluetooth
      import_tasks: tasks/configure-bt.yml

    - name: Configure WiFi
      import_tasks: tasks/configure-wifi.yml

    - name: Install Docker
      import_tasks: tasks/install-docker.yml

    - name: Clean unused dependencies
      ansible.builtin.apt: autoremove=yes

  vars:
    swap_enabled: no
    bt_enabled: no
    wifi_enabled: no
    timezone: America/New_York
