---
- hosts: pi
  become: true

  roles:
    - raspi_config

  vars:
    firmware_update: true

    hostname: rpi01

    mount_tmpfs:
      - { path: "/tmp", size: "512m", options: "nodev,nosuid" }
      - { path: "/var/log", size: "512m", options: "nodev,noexec,nosuid" }

    timezone: America/New_York

    swap:
      enabled: false

    bluetooth:
      enabled: false

    wireless:
      enabled: false

    # wireless:
    #   country: US
    #   ssid: MY_NETWORK_SSID
    #   psk: my_secret_password

    overclock:
      cpu: true
      gpu: false

    ssh:
      enabled: true
      pub_key_file:
        - ~/.ssh/id_rsa.pub
      options:
        - "AllowUsers {{ ansible_ssh_user }}"
        - "PasswordAuthentication no"
        - "PermitRootLogin no"
        - "StrictModes yes"
        - "X11Forwarding no"
        - "ChallengeResponseAuthentication no"
        - "UsePAM no"
        - "PermitEmptyPasswords no"
