---
- name: Install minecraft server
  become: true
  block:
    - name: Create minecraft user
      ansible.builtin.user:
        name: minecraft
        state: present
        create_home: true
        home: /home/minecraft

    - name: Install Java runtime
      ansible.builtin.apt:
        name: default-jre
        state: present

    - name: Check if Minecraft server binary already installed
      ansible.builtin.stat:
        path: "/home/minecraft/server.jar"
      register: server_stat

    - name: Get Minecraft server download URL
      ansible.builtin.uri:
        url: download_page_url
        return_content: true
      register: download_page
      when: not server_stat.stat.exists

    - name: Extract download URL
      ansible.builtin.set_fact:
        download_url: "{{ download_page.content | regex_search(binary_url_regex) }}"
      when: not server_stat.stat.exists

    - name: Download Minecraft server binary
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "/home/minecraft/server.jar"
        mode: 644
        owner: minecraft
      when: not server_stat.stat.exists

#     - name: Configure server settings

#     - name: Configure auto-start
