---
- name: Install minecraft server
  become: true
  block:
    - name: Create minecraft user
      ansible.builtin.user:
        name: minecraft
        state: present
        create_home: true
        home: /home/minecraft

    - name: Install Java runtime
      ansible.builtin.apt:
        name: default-jre
        state: present

    - name: Check if Minecraft server binary already installed
      ansible.builtin.stat:
        path: "/home/minecraft/server.jar"
      register: minecraft_server_stat

    - name: Get Minecraft server download URL
      ansible.builtin.uri:
        url: download_page_url
        return_content: true
      register: minecraft_download_page
      when: not minecraft_server_stat.stat.exists

    - name: Extract download URL
      ansible.builtin.set_fact:
        minecraft_download_url: "{{ minecraft_download_page.content | regex_search(binary_url_regex) }}"
      when: not minecraft_server_stat.stat.exists

    - name: Download Minecraft server binary
      ansible.builtin.get_url:
        url: "{{ minecraft_download_url }}"
        dest: "/home/minecraft/server.jar"
        mode: '0644'
        owner: minecraft
      when: not minecraft_server_stat.stat.exists

    - name: Copying EULA
      ansible.builtin.copy:
        src: templates/eula.txt
        dest: /home/minecraft/eula.txt
        owner: minecraft
        mode: '0644'

#     - name: Configure auto-start
