---
- name: Reboot host
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"

- name: Reconfigure wlan interface
  ansible.builtin.command: wpa_cli -i wlan0 reconfigure
  changed_when: true

- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
