---
- name: reboot host
  reboot:
    msg: "Reboot initiated by Ansible"

- name: reconfigure wlan interface
  ansible.builtin.command: wpa_cli -i wlan0 reconfigure

- name: restart sshd
  service:
    name: ssh
    state: restarted
