---
- name: Reboot host
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible"

- name: Reconfigure wlan interface
  ansible.builtin.command: wpa_cli -i wlan0 reconfigure

- name: Restart sshd
  service:
    name: ssh
    state: restarted
