---
- name: Bluetooth - On/Off.
  when: bluetooth is defined
  become: true
  ansible.builtin.lineinfile:
    dest: "{{ boot_config_file }}"
    regexp: "^#?dtoverlay=disable-bt"
    line: "dtoverlay=disable-bt"
    state: "{{ bluetooth | ternary('absent', 'present') }}"
  notify: reboot host
