---
- name: Firmware update
  become: true
  block:
    - name: Firmware - ensure rpi-eeprom-update is installed.
      ansible.builtin.apt:
        name: rpi-eeprom
        state: present

    - name: Firmware - check if EEPROM update required.
      ansible.builtin.command: rpi-eeprom-update
      register: raspi_config_rpi_eeprom_update_result
      changed_when: false
      check_mode: false
      failed_when:
        - raspi_config_rpi_eeprom_update_result.rc != 0
        - raspi_config_rpi_eeprom_update_result.rc != 1

    - name: Firmware - schedule EEPROM update.
      when: raspi_config_rpi_eeprom_update_result.rc == 1
      ansible.builtin.command: rpi-eeprom-update -a
      changed_when: true
      notify: reboot host
