---
- name: OS upgrade
  ansible.builtin.import_tasks: tasks/system.yml

- name: Firmware update
  ansible.builtin.import_tasks: tasks/firmware.yml

- name: Hostname setup
  ansible.builtin.import_tasks: tasks/hostname.yml

- name: SSH setup
  ansible.builtin.import_tasks: tasks/ssh.yml

- name: Bluetooth setup
  ansible.builtin.import_tasks: tasks/bluetooth.yml

- name: WiFi setup
  ansible.builtin.import_tasks: tasks/wireless.yml

- name: Mount tmpfs points
  ansible.builtin.import_tasks: tasks/tmpfs.yml

- name: Swap file setup
  ansible.builtin.import_tasks: tasks/swap.yml

- name: Overclock setup
  ansible.builtin.import_tasks: tasks/overclock.yml
