---
- name: SSH - enabled/disabled
  when: ssh.enabled is defined
  become: true
  ansible.builtin.systemd:
    name: ssh
    state: "started"
    enabled: true

- name: SSH - adding pub keys
  when: ssh.pub_key_file is defined
  become: true
  ansible.posix.authorized_key:
    user: "{{ ssh.user | default(ansible_user) }}"
    key: "{{ lookup('file', item) }}"
    state: present
    manage_dir: true
  with_list: "{{ ssh.pub_key_file }}"

- name: SSH - options
  when: ssh.options is defined
  become: true
  ansible.builtin.lineinfile:
    path: "{{ sshd_config_file }}"
    regexp: "^{{ item | regex_search('^([^ ]+)') }}"
    line: "{{ item }}"
    state: present
    validate: 'sshd -T -f %s'
  loop: "{{ ssh.options }}"
  notify: restart sshd
