---
- name: Swap file setup
  become: true
  block:
    - name: Swap file - service is started/stopped.
      when: swap.enabled is defined
      ansible.builtin.systemd:
        name: dphys-swapfile
        state: "{{ swap.enabled | ternary('started', 'stopped') }}"
        enabled: "{{ swap.enabled }}"

    - name: Swap file - setup swap file size
      when: swap.size is defined
      block:
        - name: Swap file - check swap size.
          command: "grep ^CONF_SWAPSIZE={{ swap.size }}$ {{ dphys_swapfile }}"
          changed_when: false
          failed_when: false
          register: get_swap_size_command_result

        - name: Swap file - set proper swap file size
          when: get_swap_size_command_result.rc == 1
          block:
            - name: Swap file - turn swap off.
              command: "dphys-swapfile swapoff"
              changed_when: false

            - name: Swap file - set swap size.
              ansible.builtin.lineinfile:
                path: "{{ dphys_swapfile }}"
                regexp: "^#?CONF_SWAPSIZE="
                line: "CONF_SWAPSIZE={{ swap.size }}"
                state: present

            - name: Swap file - apply new swap size
              command: "dphys-swapfile setup"
              register: swapfile_setup_out
              changed_when: "'keeping it' not in swapfile_setup_out.stdout"

            - name: Swap file - turn swap on
              command: "dphys-swapfile swapon"
              changed_when: false
